# Generated by Django 3.0.2 on 2020-02-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_no', models.CharField(max_length=200, null=True, verbose_name='组织编码')),
                ('org_name', models.CharField(max_length=200, null=True, verbose_name='组织名称')),
                ('create_date', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(null=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'usr_organization',
            },
        ),
    ]
