# Generated by Django 3.0.2 on 2020-02-12 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('create_user', models.UUIDField(null=True, verbose_name='创建人')),
                ('modify_date', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('modify_user', models.UUIDField(null=True, verbose_name='修改人')),
                ('status', models.CharField(default='1', max_length=1, verbose_name='状态')),
                ('pos_no', models.CharField(max_length=200, null=True, verbose_name='岗位编码')),
                ('pos_name', models.CharField(max_length=200, null=True, verbose_name='岗位名称')),
            ],
            options={
                'db_table': 'sys_position',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('create_user', models.UUIDField(null=True, verbose_name='创建人')),
                ('modify_date', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('modify_user', models.UUIDField(null=True, verbose_name='修改人')),
                ('status', models.CharField(default='1', max_length=1, verbose_name='状态')),
                ('user_no', models.CharField(max_length=200, null=True, verbose_name='用户账户')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='用户姓名')),
                ('age', models.IntegerField(null=True, verbose_name='用户年龄')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='用户密码')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('create_user', models.UUIDField(null=True, verbose_name='创建人')),
                ('modify_date', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('modify_user', models.UUIDField(null=True, verbose_name='修改人')),
                ('status', models.CharField(default='1', max_length=1, verbose_name='状态')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoAjax.Position')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoAjax.User')),
            ],
            options={
                'db_table': 'sys_userposition',
            },
        ),
    ]
