# Generated by Django 3.0.2 on 2020-01-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAjax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserName',
            field=models.CharField(default='', max_length=200, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=200, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserNO',
            field=models.CharField(default='', max_length=200, verbose_name='用户账户'),
        ),
    ]
