# Generated by Django 3.0.2 on 2020-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAjax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[(1, '有效'), (0, '无效')], default=1, max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(1, '有效'), (0, '无效')], default=1, max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='status',
            field=models.CharField(choices=[(1, '有效'), (0, '无效')], default=1, max_length=1, verbose_name='状态'),
        ),
    ]
