# Generated by Django 3.0.2 on 2020-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAjax', '0005_auto_20200201_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
    ]
