# Generated by Django 3.0.2 on 2020-01-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAjax', '0006_auto_20200201_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modify_date',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
    ]
