# Generated by Django 3.0.2 on 2020-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAjax', '0007_user_modify_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_no', models.CharField(max_length=200, null=True, verbose_name='岗位编码')),
                ('pos_name', models.CharField(max_length=200, null=True, verbose_name='岗位名称')),
                ('create_date', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(null=True, verbose_name='修改时间')),
            ],
        ),
    ]
