# Generated by Django 3.0.2 on 2020-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAjax', '0008_postion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.CharField(max_length=200, null=True, verbose_name='用户账户')),
                ('pos_no', models.CharField(max_length=200, null=True, verbose_name='岗位编码')),
                ('create_date', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(null=True, verbose_name='修改时间')),
            ],
        ),
    ]
